security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        epci_provider:
            entity:
                class: App\Entity\EPCI
                property: token
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        ping:
            pattern: ^/ping$
            security: false
        
        api:
            pattern: ^/
            stateless: true
            provider: epci_provider
            custom_authenticators:
                - App\Security\ApiTokenAuthenticator
                
    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/ping$, roles: IS_AUTHENTICATED_ANONYMOUSLY}


