security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        epci_provider:
            entity:
                class: App\Entity\EPCI
                property: token
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/accesscontrolapi
            stateless: true
            provider: epci_provider
            custom_authenticators:
                - App\Security\ApiTokenAuthenticator
    access_control:
        - { path: ^/accesscontrolapi, roles: IS_AUTHENTICATED_FULLY }
