security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        epci_provider:
            entity:
                class: App\Entity\EPCI
                property: token
    firewalls:
        api:
            pattern: ^/accesscontrolapi
            stateless: true
            provider: epci_provider
            custom_authenticators:
                - App\Security\ApiTokenAuthenticator

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        ping:
            pattern: ^/ping$
            security: false
                
    access_control:
        - { path: ^/accesscontrolapi, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/ping$, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        # - { path: ^/admin, roles: ROLE_ADMIN }
        


