version: '3.8'

services:
  php:
    build:
      context: .                # Contexte pour le Dockerfile PHP
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"

  nginx:
    image: nginx:latest        # Utiliser l'image officielle de Nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www              # Monter le répertoire de l'application
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Monter le fichier de configuration Nginx
    depends_on:
      - php

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3308:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
